name: Deploy dorm bot web client to Heroku


on:
  push:
    paths:
      - 'web_client/**'
    branches: [ dev ]

jobs:
  deploy:
    env:
      workdir: ./web_client
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
       
     - uses: akhileshns/heroku-deploy@v3.4.6
       with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: ${{secrets.HEROKU_APP_NAME_WEB_CLIENT}}
         heroku_email: ${{secrets.HEROKU_EMAIL}}
         appdir: "web_client"
         branch: "dev"
